apiVersion: v1
kind: Service
metadata:
  name: yankiservice
  labels:
    app: yankiservice
    service: yankiservice
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    service: yankiservice